# Numpy: a fast lookup

Numpy offre una struttura dati molto importante: gli array n-dimensionali. A differenza delle liste native di Python (che mantengono riferimenti a oggetti e i cui valori sono sparsi in memoria) gli array n-dimensionali di Numpy sono strutture *omogenee* che occupano celle di memoria contigue.

In [2]:
# Installing NumPy
# !pip install numpy

In [3]:
import numpy as np

In [4]:
'''
Let's define a utility function that will be useful later on to inspect our numpy arrays.
'''
def describe(a):
  """
  Description of the array a
  
  Parameters
  ----------
    a : numpy array
  """
  print("data:\n{}\nshape:{}\ndtype: {}".format(a, a.shape, a.dtype))

# Utility function to print horizontal rules
hrule = lambda x : "="*x

Generiamo un array bidimensionale (una matrice) 4x5 di elementi random tra 0 e 10.

In [5]:
# create a random matrix of 4x5 dimension with
# 20 points drawn from an uniform distribution 
# defined in the interval (0,10]
data = np.random.randint(0,10,20).reshape(4,5)
data

array([[6, 6, 6, 8, 6],
       [6, 9, 8, 5, 7],
       [2, 2, 3, 8, 2],
       [0, 9, 0, 5, 0]], dtype=int32)

Gli array n-dimensionali di numpy devono essere una struttura dati omogenea, sia dal punto di vista del tipo di dati (*dtype*) che dal punto di vista della dimensione (*shape*)

In [6]:
# Omogeneità per i dtype
data2 = np.array([[1,0.2,3,4], [1,2,3,4]]) # un float -> tutti float
describe(data2)

# Casting tramite la funzione astype
data_float = data.astype(np.object_)
describe(data_float)

data:
[[1.  0.2 3.  4. ]
 [1.  2.  3.  4. ]]
shape:(2, 4)
dtype: float64
data:
[[6 6 6 8 6]
 [6 9 8 5 7]
 [2 2 3 8 2]
 [0 9 0 5 0]]
shape:(4, 5)
dtype: object


In [7]:
# Omogeneità per la shape + imposizione del dtype
data2_ = np.array([[1,2,3,4], [1,2,3,4,5]], dtype='object') # non conserva le due liste come strutture omogenee
data2_

array([list([1, 2, 3, 4]), list([1, 2, 3, 4, 5])], dtype=object)

## Inizializzazione arrays

Oltre a passare direttamente una lista Python, ci sono altri modi per inizializzare un array in Numpy. Tra questi:
| Function   | Description |
|---|---|
| asarray | Convert input to ndarray, but do not copy if the input is already an ndarray |
| arange |Like the built-in range but returns an ndarray instead of a list | 
|ones, ones_like |Produce an array of all 1’s with with the same shape and dtype of the given array|
|zeros, zeros_like | Like ones but with zeros | 
| eye, identity |  Create a square N x N identity matrix |

In [8]:
print(np.zeros(10)) # create an array of 10 elements
print(np.zeros((2,2))) # create a multidimensional array 2x2
print(hrule(30))

# All the number within (0,10]
# with increment 2
print(np.arange(0,10,2))
print(hrule(30))

# Identity matrix
print(np.eye(3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[0 2 4 6 8]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Accesso

### Indexing & Slicing

Anche con gli array Numpy è possibile fare lo slicing come in Python. Tuttavia, a differenza dello slicing in Python, in Numpy lo slicing ritorna una *vista* dell'array originale e non una copia. Per lavorare su una copia bisogna usare il metodo `copy`

In [9]:
# Definisco un array con gli elementi da 0 a 10 (escluso)
arr = np.arange(10)
print(arr)
print(hrule(10))

# Stampo gli elementi dal quinto all'ottavo (escluso)
print(arr[5:8])
print(hrule(10))

# La modifica attraverso slicing ha effetti sull'array originale
arr[0:1] = 10
print(arr)
print(hrule(10))

# Per evitare problemi di modifiche non voluti bisogna usare copy()
_arr = arr.copy()
_arr[1:2] = 20
print(_arr, arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[10  1  2  3  4  5  6  7  8  9]
[10 20  2  3  4  5  6  7  8  9] [10  1  2  3  4  5  6  7  8  9]


Una caratteristica peculiare degli array numpy è che permette di assegnare dei valori scalari agli array (o a sue porzioni). Questo viene fatto tramite un'operazione detta di **broadcast**

In [10]:
arr[0:5] = 10
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

Numpy permette di fare slicing anche su array di dimensione generica

In [11]:
print(data)
print(hrule(10))

# Accedo all'elemento [0, 1]
print(data[0,1])
print(hrule(10))

# Prendo la prima riga
print("Modo 1:", data[0, :])  # `:` means: "give me the entire axis!"
print("Modo 2:", data[0])
print(hrule(10))

# Slicing per prendere la prima, seconda e terza colonna
print(data[:, 1:4])

[[6 6 6 8 6]
 [6 9 8 5 7]
 [2 2 3 8 2]
 [0 9 0 5 0]]
6
Modo 1: [6 6 6 8 6]
Modo 2: [6 6 6 8 6]
[[6 6 8]
 [9 8 5]
 [2 3 8]
 [9 0 5]]


Ecco un esempio con un array tridimensionale.

In [12]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) # 2 x 2 x 3 array
print(arr3d)
print(hrule(10))

describe(arr3d[0])  # take the first element on the first dimension (2x3) array
print(hrule(10))

# take the first element on the second axis with respect to the entire first axis
describe(arr3d[:,0]) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
data:
[[1 2 3]
 [4 5 6]]
shape:(2, 3)
dtype: int64
data:
[[1 2 3]
 [7 8 9]]
shape:(2, 3)
dtype: int64


## Boolean Indexing (maschere)

In Numpy possiamo confrontare un array elemento per elemento rispetto a una condizione logica data. Il risultato di tale confronto è la cosiddetta *maschera*, un array avente la stessa shape di quello originale che presenta true in corrispondenza dei valori che soddisfano la condizione, false viceversa.

Una volta ottenuta la maschera è possibile ritornare un nuovo array avente solo gli elementi che soddisfano la condizione con una semplice operazione di indicizzazione.

In [13]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
mask = (names=="Bob") | (names=="Will")
print(mask)
print(names[mask])

[ True False  True  True  True False False]
['Bob' 'Will' 'Bob' 'Will']


Volendo possiamo anche vedere se ci sono elementi che rispettano una condizione utilizzando `any`

In [16]:
np.any(names=="Jeff")

np.False_

Possiamo anche estrarre le posizioni dell'array dove sono presenti gli elementi che corrispondono a una condizione

In [17]:
np.argwhere(names=="Bob")

array([[0],
       [3]])

## Fancy indexing

In [ ]:
data = np.arange(20).reshape(4, 5)
print(data)
print()
print(data[[1,1,0,0],[0,1,0,1]]) # data[1,0], data[1,1], data[0,0], data[0,1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

[5 6 0 1]


## Universal Functions

An universal function is a function that performs a certain operation upon every element in an array.

In [22]:
arr = np.power(np.arange(10), 2) # param1: scalar or array, param2: exp
print(arr)
describe(np.sqrt(arr)) 

[ 0  1  4  9 16 25 36 49 64 81]
data:
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
shape:(10,)
dtype: float64


There are several functions that perform element-wise operation over an array. These are divided into two groups: unary functions and binary functions.

## Expresing Conditional Logic as Array Operations

In numpy we can express a ternary expresion x if condition else y using the simple function "where".

Create  a list $L = [l_1, l_2 \dots l_n]$ such that
$$
 l_i = \left\{\begin{array}{lr}
        x_i & \text{if } cond_i \text{ is True} \\
        y_i & \text{otherwise } 
        \end{array}\right.
$$

In [23]:
x = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
y = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
np.where(cond, x, y)

array([1.1, 2.2, 1.3, 1.4, 2.5])