# Numpy: a fast lookup

Numpy offre una struttura dati molto importante: gli array n-dimensionali. A differenza delle liste native di Python (che mantengono riferimenti a oggetti e i cui valori sono sparsi in memoria) gli array n-dimensionali di Numpy sono strutture *omogenee* che occupano celle di memoria contigue.

In [1]:
# Installing NumPy
# !pip install numpy

In [4]:
import numpy as np

In [6]:
'''
Let's define a utility function that will be useful later on to inspect our numpy arrays.
'''
def describe(a):
  """
  Description of the array a
  
  Parameters
  ----------
    a : numpy array
  """
  print("data:\n{}\nshape:{}\ndtype: {}".format(a, a.shape, a.dtype))

# Utility function to print horizontal rules
hrule = lambda x : "="*x

Generiamo un array bidimensionale (una matrice) 4x5 di elementi random tra 0 e 10.

In [5]:
# create a random matrix of 4x5 dimension with
# 20 points drawn from an uniform distribution 
# defined in the interval (0,10]
data = np.random.randint(0,10,20).reshape(4,5)
data

array([[2, 4, 4, 5, 9],
       [6, 8, 9, 6, 2],
       [4, 9, 4, 6, 0],
       [6, 7, 6, 0, 6]], dtype=int32)

Gli array n-dimensionali di numpy devono essere una struttura dati omogenea, sia dal punto di vista del tipo di dati (*dtype*) che dal punto di vista della dimensione (*shape*)

In [ ]:
# Omogeneità per i dtype
data2 = np.array([[1,0.2,3,4], [1,2,3,4]]) # un float -> tutti float
describe(data2)

# Casting tramite la funzione astype
data_float = data.astype(np.float128)
describe(data_float)

data:
[[1.  0.2 3.  4. ]
 [1.  2.  3.  4. ]]
shape:(2, 4)
dtype: float64


AttributeError: module 'numpy' has no attribute 'O'

In [ ]:
# Omogeneità per la shape
data2_ = np.array([[1,2,3,4], [1,2,3,4,5]], dtype='object') # non conserva le due liste come strutture omogenee
data2_

array([list([1, 2, 3, 4]), list([1, 2, 3, 4, 5])], dtype=object)

## Inizializzazione arrays

Oltre a passare direttamente una lista Python, ci sono altri modi per inizializzare un array in Numpy. Tra questi:
| Function   | Description |
|---|---|
| asarray | Convert input to ndarray, but do not copy if the input is already an ndarray |
| arange |Like the built-in range but returns an ndarray instead of a list | 
|ones, ones_like |Produce an array of all 1’s with with the same shape and dtype of the given array|
|zeros, zeros_like | Like ones but with zeros | 
| eye, identity |  Create a square N x N identity matrix |

In [10]:
print(np.zeros(10)) # create an array of 10 elements
print(np.zeros((2,2))) # create a multidimensional array 2x2
print(hrule(30))

# All the number within (0,10]
# with increment 2
print(np.arange(0,10,2))
print(hrule(30))

# Identity matrix
print(np.eye(3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[0 2 4 6 8]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
